language: node_js
node_js:
    - "10"
install:
  - npm install vuepress
script:
  - npm run docs:build
notifications:
    email: false
cache:
    directories:
        - "node_modules"
deploy:
  provider: pages
  skip-cleanup: true
  local_dir: docs/.vuepress/dist
  github-token: $GITHUB_TOKEN # a token generated on github allowing travis to push code on you repository
  keep-history: true
  repo: leonidlezner/leonidlezner.github.io
  on:
    branch: master
